name: Deploy KanPlan Web

on:
  push:
    branches:
      [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build  # This creates the production build in the "build/" folder

    - name: Checkout code
      uses: actions/setup-node@v4

    - name: Create tarball
      run: tar --no-same-permissions -cvf publish.tar ./build
      
    - name: Deploy to KanPlan Web
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        source: './publish.tar'
        target: '/var/www/html/KanPlan.Web'
        port: 22
